### ISSUE TITLE
Data in npy format or source code to process the data

### ISSUE THREAD

**Issue by fazhmshily** [xuczhang/tapnet#8]
Hi, thanks for uploading the model codes. Could you please publish your 30 datasets in npy format (as the ones under dataset/NATOPS) or the source code to process the datasets (normalization and so on) so that we can make fair comparisons with other models? 

Thank you very much!

**Comment by xuczhang** [comment]
I have upload all the preprocessed data into google drive. You can find the link in README.md file. Thanks.
